#!/bin/bash

# Up -- Debian/Ubuntu Update Tool (Version 1.0)


# stop execution if there is any error
set -e

# Functions:

update() {

echo "Starting full system update..."
sudo apt update
sudo apt full-upgrade -yy

}

clean() {

echo "Removing apt cache packages that can no longer be downloaded..."
sudo apt autoclean

}

remove() {

echo "Removing orpahned packages..."
sudo apt autoremove -yy
sudo apt remove --purge $(dpkg -l | grep "^rc" | awk '{print $2}') -yy

}

leave() {

echo "--------------------"
echo "- Update Complete! -"
echo "--------------------"
exit

}

up_help() {

less << _EOF_
 Up -- Debian/Ubuntu Update Tool (Version 1.3)  -help
 Up is a tool that automates the update procedure for Debian and Ubuntu based
 Linux systems.
 Press "q" to exit this Help page.
 Commands:
    up = full system update.
    Running "up" with no options will update the apt cache and then perform a
    full distribution update automatically.
    up --remove = full system update with orphaned packages removed.
    up --clean = full system update with full cleanup.
    Adding the "--clean" option will invoke the apt commands to search for and
    remove locally cached packages that are no longer in the repositories and
    remove orphaned packages that are no longer needed by programs.
    The "--remove" option only removes orphaned packages, leaving the apt cache
    alone.
    up --help = shows this help page.
 For Practice purposes only
_EOF_

}

# Execution.


echo "Up -- Debian/Ubuntu Update Tool (Version 1.0)"

# Update and clean:

if [ "$1" == "--clean" ]; then
    update
    remove
    clean
    leave
fi

# Update and remove orphaned packages:

if [ "$1" == "--remove" ]; then
    update
    remove
    leave
fi

if [ "$1" == "--help" ]; then
    up_help
    exit
fi

# Check for invalid argument

if  [ -n "$1"  ]; then
    echo "Up Error: Invalid argument. Try 'up --help' for more info." >&2
    exit 1
fi

update
leave
